### ISSUE TITLE
fa_icon span request

### ISSUE THREAD

**Issue by peyterkim** [bokmann/font-awesome-rails#140] opened 2015-05-28 15:22 UTC
Could you make a helper that has the same function as fa_icon but instead of converting it to an i-tag, make it a span-tag. Like so, ```<span class="fa fa-icon"></span>```

**Comment by rmm5t** [comment] 2015-05-28 15:39
Duplicate of #62.  Please read through the _entire_ discussion of that issue.  If you can make a compelling case as to why this should be re-visited, we can continue the discussion here.

**Closed by rmm5t** 2015-05-28 15:39 UTC
Labels: duplicate
